FROM openjdk:21-ea-jdk-slim
VOLUME /tmp
COPY target/*.jar app.jar
ENV EUREKA_URL=http://ms-registryserver:8761/eureka/
ENV KAFKA_URL=http://msg-broker:9092
ENV MONGO_HOST=mongo-db
ENTRYPOINT ["java","-jar","/app.jar"]