FROM openjdk:21-ea-jdk-slim
VOLUME /tmp
COPY target/*.jar app.jar
ENV EUREKA_URL=http://ms-registryserver:8761/eureka/
ENV CONFIG_SERVER_URL=http://ms-config-server:7777
ENV OTLP_METRICS_URL=http://otel-collector:4318/v1/metrics
ENV OTLP_TRACING_URL=http://otel-collector:4318/v1/traces
ENV KAFKA_URL=msg-broker:9092
ENTRYPOINT ["java","-jar","/app.jar"]